### ISSUE TITLE
Windows WebServer?

### ISSUE THREAD

**Issue by serrulate** [coatless-quarto/r-shinylive-demo#13]
Hello, 

your tutorial has been so helpful. I was wondering if you have any experience with publishing to a windows web server. 
I have been able to create and render the sample documents, when i try and deploy the application to a windows webserver i'm hitting some roadblocks most recently i'm receiving. the following...any thoughts? 

R.bin.js:2061 Uncaught (in promise) Error: Couldn't load /sandbox/docs/site_libs/quarto-contrib/shinylive-0.5.0/shinylive/webr/vfs/usr/lib/R/library/translations/DESCRIPTION. Status: 404
    at LazyUint8Array.LazyUint8Array_cacheLength [as cacheLength] (R.bin.js:2061:92092)
    at LazyUint8Array.get (R.bin.js:2061:94070)
    at FSNode.get [as usedBytes] (R.bin.js:2061:94562)
    at Object.getattr (R.bin.js:2061:47454)
    at stat (R.bin.js:2061:78581)
    at Object.doStat (R.bin.js:2061:95962)
    at ___syscall_stat64 (R.bin.js:2061:243932)
    at R.bin.wasm:0x307ae2
    at R.bin.wasm:0x320ea4
    at R.bin.wasm:0x1e2db6

**Comment by coatless** [comment]
The choice of webserver doesn't matter. 

This looks like a file is missing as you're getting a 404 (file not found) error. 

You probably want to raise this as an issue over at the shinylive repository: 

https://github.com/posit-dev/r-shinylive/
